// These styles apply to every route in the application
import Nav from "./nav";
import Footer from "./footer";
import Sidebar from "./sidebar";
import { useRouter } from "next/dist/client/router";
import { useState } from "react";
import { ReduxProvider } from "../redux/provider";
import { AppProvider } from "./Tourcontext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const [page, setPage] = useState(router.pathname);

  return (
    <div>
      <ReduxProvider>
        <AppProvider>
          <Nav />
          {/* <Sidebar /> */}
          {/* if page is login or register then dont show sidebar else show it */}
          {page === "/login" || page === "/register" ? null : <Sidebar />}
          {children}
          {/* <Footer /> */}
        </AppProvider>
      </ReduxProvider>
    </div>
  );
}
